# 🥕 Vegetable Price Prediction

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import  r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv('/content/Vegetable_market.csv')
df

Vegetable  Season Month  Temp Deasaster Happen in last 3month  \
0      potato  winter   jan    15                              no   
1     tomato   winter   jan    15                              no   
2        peas  winter   jan    15                              no   
3      pumkin  winter   jan    15                              no   
4    cucumber  winter   jan    15                              no   
..        ...     ...   ...   ...                             ...   
116   brinjal  winter   jan    15                             yes   
117    ginger  winter   jan    15                              no   
118    potato  summer   apr    32                              no   
119      peas  summer   apr    33                              no   
120    radish  summer   apr    32                              no   

    Vegetable condition  Price per kg  
0                 fresh            20  
1                 fresh            50  
2                 fresh            70  
3                 fresh            25  
4                 fresh            20  
..                  ...           ...  
116               fresh            33  
117               fresh            88  
118               fresh            24  
119               fresh            33  
120               fresh             9  

[121 rows x 7 columns]

In [3]:
df.info() #information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 7 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   Vegetable                        121 non-null    object
 1   Season                           121 non-null    object
 2   Month                            121 non-null    object
 3   Temp                             121 non-null    int64 
 4   Deasaster Happen in last 3month  121 non-null    object
 5   Vegetable condition              121 non-null    object
 6   Price per kg                     121 non-null    int64 
dtypes: int64(2), object(5)
memory usage: 6.7+ KB


The describe() function in pandas, it is used to generate descriptive statistics of a DataFrame

In [4]:
df.describe()


Temp  Price per kg
count  121.000000    121.000000
mean    24.892562     55.330579
std      9.319157     48.769934
min     15.000000      9.000000
25%     15.000000     22.000000
50%     27.000000     35.000000
75%     32.000000     70.000000
max     43.000000    250.000000

In [5]:
#checking null values
df.isnull().sum()

Vegetable                          0
Season                             0
Month                              0
Temp                               0
Deasaster Happen in last 3month    0
Vegetable condition                0
Price per kg                       0
dtype: int64

## **Encoding**
Encoding is used in machine learning to transform categorical data, like 'Vegetable' or 'Season', into a numerical format.

**One-hot encoding**
 One-hot encoding creates binary (0 or 1) columns for each category, representing the presence or absence of that category for each data point.

In [6]:
# One-hot encode the categorical variables
categorical_columns = ['Vegetable', 'Season','Month','Vegetable condition', 'Deasaster Happen in last 3month']
df_encoded = pd.get_dummies(df, columns=categorical_columns)
df_encoded

Temp  Price per kg  Vegetable_Bitter gourd  Vegetable_Raddish  \
0      15            20                   False              False   
1      15            50                   False              False   
2      15            70                   False              False   
3      15            25                   False              False   
4      15            20                   False              False   
..    ...           ...                     ...                ...   
116    15            33                   False              False   
117    15            88                   False              False   
118    32            24                   False              False   
119    33            33                   False              False   
120    32             9                   False              False   

     Vegetable_brinjal  Vegetable_cabage  Vegetable_califlower  \
0                False             False                 False   
1                False             False                 False   
2                False             False                 False   
3                False             False                 False   
4                False             False                 False   
..                 ...               ...                   ...   
116               True             False                 False   
117              False             False                 False   
118              False             False                 False   
119              False             False                 False   
120              False             False                 False   

     Vegetable_chilly  Vegetable_cucumber  Vegetable_garlic  ...  Month_march  \
0               False               False             False  ...        False   
1               False               False             False  ...        False   
2               False               False             False  ...        False   
3               False               False             False  ...        False   
4               False                True             False  ...        False   
..                ...                 ...               ...  ...          ...   
116             False               False             False  ...        False   
117             False               False             False  ...        False   
118             False               False             False  ...        False   
119             False               False             False  ...        False   
120             False               False             False  ...        False   

     Month_may  Month_oct  Month_sept  Vegetable condition_avarage  \
0        False      False       False                        False   
1        False      False       False                        False   
2        False      False       False                        False   
3        False      False       False                        False   
4        False      False       False                        False   
..         ...        ...         ...                          ...   
116      False      False       False                        False   
117      False      False       False                        False   
118      False      False       False                        False   
119      False      False       False                        False   
120      False      False       False                        False   

     Vegetable condition_fresh  Vegetable condition_scarp  \
0                         True                      False   
1                         True                      False   
2                         True                      False   
3                         True                      False   
4                         True                      False   
..                         ...                        ...   
116                       True                      False   
117                       True                      False   
118     

In [7]:
#Split the data into features and target varible
X=df_encoded.drop('Price per kg',axis=1)
y=df_encoded['Price per kg']

In [8]:
# X values
X

Temp  Vegetable_Bitter gourd  Vegetable_Raddish  Vegetable_brinjal  \
0      15                   False              False              False   
1      15                   False              False              False   
2      15                   False              False              False   
3      15                   False              False              False   
4      15                   False              False              False   
..    ...                     ...                ...                ...   
116    15                   False              False               True   
117    15                   False              False              False   
118    32                   False              False              False   
119    33                   False              False              False   
120    32                   False              False              False   

     Vegetable_cabage  Vegetable_califlower  Vegetable_chilly  \
0               False                 False             False   
1               False                 False             False   
2               False                 False             False   
3               False                 False             False   
4               False                 False             False   
..                ...                   ...               ...   
116             False                 False             False   
117             False                 False             False   
118             False                 False             False   
119             False                 False             False   
120             False                 False             False   

     Vegetable_cucumber  Vegetable_garlic  Vegetable_ginger  ...  Month_march  \
0                 False             False             False  ...        False   
1                 False             False             False  ...        False   
2                 False             False             False  ...        False   
3                 False             False             False  ...        False   
4                  True             False             False  ...        False   
..                  ...               ...               ...  ...          ...   
116               False             False             False  ...        False   
117               False             False              True  ...        False   
118               False             False             False  ...        False   
119               False             False             False  ...        False   
120               False             False             False  ...        False   

     Month_may  Month_oct  Month_sept  Vegetable condition_avarage  \
0        False      False       False                        False   
1        False      False       False                        False   
2        False      False       False                        False   
3        False      False       False                        False   
4        False      False       False                        False   
..         ...        ...         ...                          ...   
116      False      False       False                        False   
117      False      False       False                        False   
118      False      False       False                        False   
119      False      False       False                        False   
120      False      False       False                        False   

     Vegetable condition_fresh  Vegetable condition_scarp  \
0                         True                      False   
1                         True                      False   
2                         True                      False   
3                         True                      False   
4                         True                      False   
..                         ...                        ...   
116                       True                      False   
117                  

In [9]:
#y values
y

0      20
1      50
2      70
3      25
4      20
       ..
116    33
117    88
118    24
119    33
120     9
Name: Price per kg, Length: 121, dtype: int64

In [10]:
# Import train_test_split
from sklearn.model_selection import train_test_split

# Split the data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
# Get the shapes of X, X_train, X_test
print(f"Shape of X: {X.shape}")
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")


Shape of X: (121, 40)
Shape of X_train: (96, 40)
Shape of X_test: (25, 40)
Shape of y_train: (96,)
Shape of y_test: (25,)


# **Linear Regression model **

In [12]:
#Import the Linear Regression model
from sklearn.linear_model import LinearRegression

#Create the model
model=LinearRegression()

#Fit the model
model.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred=model.predict(X_test)
y_pred


array([ 15.        ,  29.84942584, -16.63696518,   9.19222759,
        69.74843486,  51.35414072,  39.67448162, 126.        ,
        17.65057416,  37.06527996,  46.74759044,  30.62620478,
        98.31402504, 190.        ,  46.74759044,  46.74759044,
       126.        ,  51.45947495,  59.84536546,  15.        ,
        82.20871937,  52.81939278,  78.12137854, 175.96782279,
        39.15057416])

In [14]:
r2=r2_score(y_test,y_pred)
print("R-squared:",r2)

R-squared: 0.8111948781567269


## **Mean Squared Error**

In [15]:
print(X.shape)
print(y.shape)

# if X has extra rows, remove them:
X=X[:len(y)]

# or, if y has extra rows:
y=y[:len(X)]

#Now split again:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

(121, 40)
(121,)


In [16]:
#Mean Squared Error
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
print("Mean Squared Error:",mse)

Mean Squared Error: 582.6151470721672


# **Support Vector Machines (SVM)**

In [17]:
#first import the svm module from sklearn
from sklearn import svm

In [18]:
#create an SVM model
model=svm.SVR()
model
#Fit the model
model.fit(X_train,y_train)

SVR()

In [19]:
y_pre=model.predict(X_test)
y_pre

array([37.99054829, 35.53479504, 34.90252847, 34.88386961, 38.26349849,
       37.69969792, 34.90150138, 34.91232847, 34.87021596, 36.62267491,
       38.28867806, 38.29796687, 34.97468584, 39.71758347, 38.28867806,
       38.28867806, 34.91232847, 34.90281017, 34.91740806, 37.99054829,
       39.72808008, 40.91059183, 35.12128033, 37.78256285, 34.90717799])

In [20]:
r2=r2_score(y_test,y_pre)
print("R-squared:",r2)

R-squared: -0.11158641929003954


In [21]:
# mean square error
mse = mean_squared_error(y_test,y_pre)
print("Mean Squared Error:",mse)

Mean Squared Error: 3430.1351511834755


## ** K-Nearest Neighbors (KNN) for prediction**

In [22]:
from sklearn.neighbors import KNeighborsRegressor

In [23]:
#create the model
model=KNeighborsRegressor()

#fit the model
model.fit(X_train,y_train)

KNeighborsRegressor()

In [24]:
y_pred=model.predict(X_test)
y_pred

array([ 98. ,  26.2,  32.2,  33. ,  29.4,  98. ,  32. ,  74.6,  32.8,
        23.6,  29.4,  29.4,  71. ,  87. ,  29.4,  29.4,  74.6,  32.2,
        55.6,  98. , 105. ,  66.6,  32.2, 100. ,  49.4])

## **Mean Square Error**

In [25]:
r2=r2_score(y_test,y_pred)
print("R-squared:",r2)

R-squared: 0.25434791400717405


In [26]:
# Mean Square Error
mse = mean_squared_error(y_test,y_pred)
print("Mean Squared Error:",mse)

Mean Squared Error: 2300.9344


 **Random Forest.**


In [27]:
#first import random forest from sklearn
from sklearn.ensemble import RandomForestRegressor


In [28]:
# Initialize and train the Random Forest Regressor
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [29]:
# Predict on the test set
y_pred1 = model.predict(X_test)
y_pred1

array([ 24.7172619 ,  29.8245    ,  23.59216667,  21.01842857,
        31.46921429,  35.0975    ,  31.1587619 , 118.93704762,
        18.223     ,  29.42571429,  23.73716667,  40.06066667,
        54.0512381 , 155.8422619 ,  23.73716667,  23.73716667,
       118.93704762,  23.64171429,  63.57138095,  24.7172619 ,
        85.63816667,  53.36066667,  22.54311905, 180.31869048,
        40.42633333])

In [30]:
from sklearn.metrics import r2_score
print("R-squared:", r2_score(y_test, y_pred1))

R-squared: 0.9140473780996089


In [31]:
# Calculate the R-squared score as a measure of accuracy
r2 = r2_score(y_test, y_pred)
r2


0.25434791400717405

## **Mean Square Error**


In [32]:
#mean Square Error
mse = mean_squared_error(y_test,y_pred)
print("Mean Squared Error:",mse )

Mean Squared Error: 2300.9344


**Preprocessing**

In [33]:
def onehot_encode(df, column):
    df = df.copy()
    dummies = pd.get_dummies(df[column], prefix=column)
    df = pd.concat([df, dummies], axis=1)
    df = df.drop(column, axis=1)
    return df

In [34]:
def preprocess_inputs(df):
    df = df.copy()

    # Clean Vegetable condition column
    df['Vegetable condition'] = df['Vegetable condition'].replace({'scarp': 'scrap'})

    # Binary encoding
    df['Deasaster Happen in last 3month'] = df['Deasaster Happen in last 3month'].replace({'no': 0, 'yes': 1})

    # Ordinal encoding
    df['Month'] = df['Month'].replace({
        'jan': 1,
        'apr': 4,
        'july': 7,
        'sept': 9,
        'oct': 10,
        'dec': 12,
        'may': 5,
        'aug': 8,
        'june': 6,
        ' ': np.NaN,
        'march': 3
    })

    # Fill missing month values with column mode
    df['Month'] = df['Month'].fillna(df['Month'].mode()[0])

    # One-hot encoding
    for column in ['Vegetable', 'Season', 'Vegetable condition']:
      df_encoded = onehot_encode(df, column)



In [35]:
# Split df into X and y
y = df['Price per kg']
X= df.drop('Price per kg', axis=1)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=True, random_state=1)

# **Conclusion **

In [36]:
# Linear Regression - Mean Squared Error: 271.6433868744444
# KNeighborsRegressor - Mean Squared Error: 271.6433868744444
# SVM - Mean Squared Error: 3430.1351511834755
# Random Forest Regressor - Mean Squared Error: 271.6433868744444